apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-test-ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-test-ci
  template:
    metadata:
      labels:
        app: springboot-test-ci
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: api
          image: andersoncmciet/springboot-test-ci:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 9090

---

apiVersion: v1
kind: Service
metadata:
  name: springboot-test-ci
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    app: springboot-test-ci
spec:
  type: ClusterIP
  ports:
    - name: springboot-test-ci
      port: 9090
  selector:
    app: springboot-test-ci